config/routes.rb
Building::Application.routes.draw do
  get '/contractors/new', controller: 'contractors', action: 'new', as: 'new_contractor'
  post '/contractors', controller: 'contractors', action: 'create'

  get '/contractors', controller: 'contractors', action: 'index', as: 'contractors'
  get '/contractors/:id', controller: 'contractors', action: 'show', as: 'contractor'

  get '/contractors/:id/edit', controller: 'contractors', action: 'edit', as: 'edit_contractor'
  put '/contractors/:id', controller: 'contractors', action: 'update'

  delete '/contractors/:id', controller: 'contractors', action: 'destroy'

  get '/projects/new', controller: 'projects', action: 'new', as: 'new_project'
  post '/projects', controller: 'projects', action: 'create'

  get '/projects', controller: 'projects', action: 'index', as: 'projects'
  get '/projects/:id', controller: 'projects', action: 'show', as: 'project'

  get '/projects/:id/edit', controller: 'projects', action: 'edit', as: 'edit_project'
  put '/projects/:id', controller: 'projects', action: 'update'

  delete '/projects/:id', controller: 'projects', action: 'destroy'

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController

  def index
    @contractors = Contractor.all
  end

  def show
    @contractor = Contractor.find_by_id(params[:id])
  end

  def new
    @contractor = Contractor.new
  end

  def create
    @contractor = Contractor.new
    @contractor.business = params[:business]
    @contractor.name = params[:name]
    @contractor.type = params[:type]
    @contractor.email = params[:email]
    @contractor.phone = params[:phone]
    @contractor.address = params[:address]
    
    if @contractor.save
            redirect_to contractors_url
          else
      render 'new'
    end
  end

  def edit
    @contractor = Contractor.find_by_id(params[:id])
  end

  def update
    @contractor = Contractor.find_by_id(params[:id])
    @contractor.business = params[:business]
    @contractor.name = params[:name]
    @contractor.type = params[:type]
    @contractor.email = params[:email]
    @contractor.phone = params[:phone]
    @contractor.address = params[:address]
    
    if @contractor.save
            redirect_to contractors_url
          else
      render 'edit'
    end
  end

  def destroy
    @contractor = Contractor.find_by_id(params[:id])
    @contractor.destroy
        redirect_to contractors_url
      end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find_by_id(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new
    @project.description = params[:description]
    @project.responsible = params[:responsible]
    @project.priority = params[:priority]
    @project.status = params[:status]
    @project.due_date = params[:due_date]
    @project.reminder = params[:reminder]
    
    if @project.save
            redirect_to projects_url
          else
      render 'new'
    end
  end

  def edit
    @project = Project.find_by_id(params[:id])
  end

  def update
    @project = Project.find_by_id(params[:id])
    @project.description = params[:description]
    @project.responsible = params[:responsible]
    @project.priority = params[:priority]
    @project.status = params[:status]
    @project.due_date = params[:due_date]
    @project.reminder = params[:reminder]
    
    if @project.save
            redirect_to projects_url
          else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find_by_id(params[:id])
    @project.destroy
        redirect_to projects_url
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contractors/edit.html.erb
<h1>Editing Contractor #<%= @contractor.id %></h1>


<%= form_tag(contractor_url(@contractor), method: 'put') do %>

  <div>
    <%= label_tag :business %><br />
    <%= text_field_tag :business, @contractor.business %>
  </div>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @contractor.name %>
  </div>

  <div>
    <%= label_tag :type %><br />
    <%= text_field_tag :type, @contractor.type %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @contractor.email %>
  </div>

  <div>
    <%= label_tag :phone %><br />
    <%= text_field_tag :phone, @contractor.phone %>
  </div>

  <div>
    <%= label_tag :address %><br />
    <%= text_field_tag :address, @contractor.address %>
  </div>

  
  <div>
    <%= submit_tag "Update Contractor" %>
  </div>

<% end %>

app/views/contractors/index.html.erb
<h1>Contractors</h1>

<p><%= link_to 'Add a New Contractor', new_contractor_url %></p>

<table class="table table-bordered table-striped table-hover">
    <thead>


    <tr>
      <th>Business</th>
      <th>Name</th>
      <th>Type</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @contractors.each do |contractor| %>
    <tr>
      <td><%= contractor.business %></td>
      <td><%= contractor.name %></td>
      <td><%= contractor.job %></td>
      <td><%= contractor.email %></td>
      <td><%= contractor.phone %></td>
      <td><%= contractor.address %></td>

      <td><%= link_to 'Show', contractor_url(contractor) %></td>
      <td><%= link_to 'Edit', edit_contractor_url(contractor) %></td>
      <td><%= link_to 'Destroy', contractor_url(contractor), method: 'delete', data: { confirm: "Do you really want to delete this contractor?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/contractors/new.html.erb
<h1>New Contractor</h1>


<%= form_tag(contractors_url, method: 'post') do %>


  <div>
    <%= label_tag :business %><br />
    <%= text_field_tag :business %>
  </div>

    <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

    <div>
    <%= label_tag :type %><br />
    <%= text_field_tag :type %>
  </div>

    <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

    <div>
    <%= label_tag :phone %><br />
    <%= text_field_tag :phone %>
  </div>

    <div>
    <%= label_tag :address %><br />
    <%= text_field_tag :address %>
  </div>

  
  <div>
    <%= submit_tag "Create Contractor" %>
  </div>
<% end %>

app/views/contractors/show.html.erb
<h1>Contractor #<%= @contractor.id %></h1>

<p>
  <b>Business:</b>
  <%= @contractor.business %>
</p>

<p>
  <b>Name:</b>
  <%= @contractor.name %>
</p>

<p>
  <b>Type:</b>
  <%= @contractor.type %>
</p>

<p>
  <b>Email:</b>
  <%= @contractor.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @contractor.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @contractor.address %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<center><%=image_tag("logo1b.gif", alt: "Image")%>
  <br> <h2><bld>The Blah Blah Association </bld></h2> </center>
<head>
  <meta charset="utf-8">
  <title>Blah Blah Building</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Building</a>
        <div class="nav-collapse">
          <ul class="nav">

            <li><%= link_to "Home", "/" %></li>
            <li><%= link_to "Projects", "/projects" %></li>
            <li><%= link_to "Contractors", "/contractors" %></li>
            <li><a href="#about">About</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <%= yield %>

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Editing Project #<%= @project.id %></h1>


<%= form_tag(project_url(@project), method: 'put') do %>

  <div>
    <%= label_tag :description %>
    <%= text_area_tag :description, @project.description %>
  </div>
<br />
  <div>
    <%= label_tag :responsible %>
    <%= text_field_tag :responsible, @project.responsible %>
  </div>
<br />
  <div>
    <%= label_tag :priority %>
    <%= text_field_tag :priority, @project.priority %>
  </div>
<br />
  <div>
    <%= label_tag :status %>
    <%= text_field_tag :status, @project.status %>
  </div>
<br />
  <div>
    <%= label_tag :due_date %>
    <%= text_field_tag :due_date, @project.due_date %>
  </div>
<br />
  <div>
    <%= label_tag :reminder %>
    <%= text_field_tag :reminder, @project.reminder %>
  </div>
<br />

  <div>
    <%= submit_tag "Update Project" %>
  </div>

<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>


<table class="table table-bordered table-striped table-hover">

  <thead>
    <tr>
      <th>Description</th>
      <th>Responsible</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Due date</th>
      <th>Reminder</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.description %></td>
      <td><%= project.responsible %></td>
      <td><%= project.priority %></td>
      <td><%= project.status %></td>
      <td><%= project.due_date %></td>
      <td><%= project.reminder %></td>

      <td><%= link_to 'Show', project_url(project) %></td>
      <td><%= link_to 'Edit', edit_project_url(project) %></td>
      <td><%= link_to 'Destroy', project_url(project), method: 'delete', data: { confirm: "Do you really want to delete this project?" } %></td>

    </tr>

  <% end %>
  </tbody>
</table>
    <p><%= link_to 'Add a New Project', new_project_url %></p>

 <div>

  <td><a class="btn btn-inverse" href="/projects/new">New Project</a></td>

  </div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<br />


<%= form_tag(projects_url, method: 'post') do %>


  <div>
    <%= label_tag :description %>
    <%= text_area_tag :description %>
  </div>

  <br />
    <div>
    <%= label_tag :responsible %>
    <%= text_field_tag :responsible %>
  </div>
  <br />
    <div>
    <%= label_tag :priority %>
    <%= text_field_tag :priority %>
  </div>
    <br />
    <div>
    <%= label_tag :status %>
    <%= text_field_tag :status %>
  </div>
  <br />
    <div>
    <%= label_tag :due_date %>
    <%= text_field_tag :due_date %>
  </div>
  <br />
    <div>
    <%= label_tag :reminder %>
    <%= text_field_tag :reminder %>
  </div>
  <br />

  <div>
    <%= submit_tag "Create Project", class: 'btn btn-primary' %>

  <td><a class="btn btn-inverse btn-small" href="/projects">Cancel</a></td>


  </div>
<% end %>

app/views/projects/show.html.erb
<h1>Project #<%= @project.id %></h1>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Responsible:</b>
  <%= @project.responsible %>
</p>

<p>
  <b>Priority:</b>
  <%= @project.priority %>
</p>

<p>
  <b>Status:</b>
  <%= @project.status %>
</p>

<p>
  <b>Due date:</b>
  <%= @project.due_date %>
</p>

<p>
  <b>Reminder:</b>
  <%= @project.reminder %>
</p>